### ISSUE TITLE
Discord export - :world: nationality is not recognised as a discord emoji

### ISSUE THREAD

**Issue by rocheGit** [skybaks/pyplanet-cup_manager#24]
When someone doesn't have any nationality specified, the discord export function returns :world: as a flag tag
Discord doesn't recognize it as an emoji, it'll need to be one of the 3 (doesn't really matter which one) :"earth_africa":, :"earth_americas": or :"earth_asia": (without the quotes) 

![image](https://user-images.githubusercontent.com/70656044/169591504-2bf57be8-e44a-45af-a17f-772b1fd37dda.png)

**Comment by skybaks** [comment]
I cant believe I never tested this 🤦

**Comment by skybaks** [comment]
I'm going to use 🌐 because its a bit more generic than choosing a specific continent.
