### ISSUE TITLE
Associate cup payouts to results

### ISSUE THREAD

**Issue by rocheGit** [skybaks/pyplanet-cup_manager#32]
It would be nice if there was a way to add a column to the results exports with the planets rewards associated to the cup

(A lot of people don't know there are even payouts for HEC since it's not mentioned anywhere on the results)

**Comment by skybaks** [comment]
For this I was also thinking we could add a chat message to each player after sending the payout that says something like

> You won {planet amount} planets for placing {placement} in {cup name}

**Comment by skybaks** [comment]
> Example output with payout specified

**test** - 99 - 14 Players
*Laps* on Test Map Laps <https://tm.mania.exchange/s/tr/121032>
:first_place: :globe_with_meridians: arn\*os\*l
:second_place: :globe_with_meridians: Tay\*.Co
:second_place: :flag_hu: DdariQ
:four: :flag_us: Rexasaurus.

Full results:
```
 1  1000  120  1:40.030  arn*os*l
 2   600  120  1:40.039  Tay*.Co
 2   600  120  1:40.039  DdariQ
 4   400  120  1:40.066  Rexasaurus.
 5   300  120  1:40.122  GrymNick
 6        120  1:50.122  Plambt
 7        120  1:50.123  Bryrie
 8        120  2:00.001  umproTM
 9        120  3:20.000  prince10bee
10        120  3:20.922  Franck_952
11        120  3:30.510  MrFunnyFun_
12        120  6:07.122  eyebo
13          6  0:12.302  player_____01
14          3  0:16.900  ZEAFUS
Spec                     zai-tm
```

**Comment by rocheGit** [comment]
Looking good!

To avoid having an empty column trailing for the non top 5 I think it would be better looking to have the payout as the last column. The usernames will also be closer to positions so less chances to misread and skip a line

Column heading could also be nice, if I wasn't familiar with trackmania cups i'd have no idea what the planets and cp count columns are

**Comment by skybaks** [comment]
Ok, I reworked it to append the payout values last. The same example from before now looks like this:

```
 1  120  1:40.030  arn*os*l     1000
 2  120  1:40.039  Tay*.Co      600
 2  120  1:40.039  DdariQ       600
 4  120  1:40.066  Rexasaurus.  400
 5  120  1:40.122  GrymNick     300
 6  120  1:50.122  Plambt
 7  120  1:50.123  Bryrie
 8  120  2:00.001  umproTM
 9  120  3:20.000  prince10bee
10  120  3:20.922  Franck_952
11  120  3:30.510  MrFunnyFun_
12  120  6:07.122  eyebo
13    6  0:12.302  player_____01
14    3  0:16.900  ZEAFUS
Spec               zai-tm
```
