### ISSUE TITLE
$m tag gets ignored by maniaplanet but not by the exporter

### ISSUE THREAD

**Issue by rocheGit** [skybaks/pyplanet-cup_manager#40]
When someone has a username with a $m in it, for example "Example$mExample", Maniaplanet ignores it and shows it as "ExampleExample" ingame. The plugin shows it a "Example$mExample" in the results export

Maybe there are other tags that glitch that way, but I didn't encounter them (yet !)

**Comment by skybaks** [comment]
Hm, im not even sure what m means. Why would someone put that in their username?

**Comment by rocheGit** [comment]
Sometimes when you mess around with your username or if you don't really know what you do and just try random things you can end up with tags that don't do anything by mistake

I also found this username that broke, but couldn't isolate why it did : $00»$f6Ootje Nack.nl .Smurfin

**Comment by skybaks** [comment]
I think that one makes sense because color codes are supposed to have 3 values for rgb after the $. I think I'll have to fix this one in pyplanet since the format functions im using is part of pyplanet itself.

**Comment by skybaks** [comment]
Related to https://github.com/PyPlanet/PyPlanet/issues/1249

**Comment by skybaks** [comment]
Resolved by https://github.com/PyPlanet/PyPlanet/pull/1268
