### ISSUE TITLE
[Pyplanet W1lla Installation] Apps.py in settings Folder.

### ISSUE THREAD

**Issue by w1lla** [skybaks/pyplanet-cup_manager#42]
#Pyplanet Cup Manager by skybaks \0/ in apps.py in settings folder.
    'pyplanet.apps.contrib.cup_manager.cup_manager', 
based on C:\tmn\pyplanet\env\Lib\site-packages\pyplanet\apps\contrib\cup_manager

Not sure if this will work properly for others, but it works for me.

**Comment by skybaks** [comment]
I dont know what this means. Is this an issue or just information?
