### ISSUE TITLE
[Multiple Scripts in 1 cup]

### ISSUE THREAD

**Issue by w1lla** [skybaks/pyplanet-cup_manager#50]
Usage of multiple scripts/gamemodes in a cup for instance use TA, and then Cup or Rounds.

**Comment by skybaks** [comment]
This is currently possible. How would you suggest combining the scores from different modes?
Also, has a competition across multiple modes ever been held before?

**Comment by w1lla** [comment]
Havent tested it yet, but would like to testrun a teams ranked way of tm2020 and then a short cupmode. Will give further details in the upcoming week

**Comment by skybaks** [comment]
What I mean to say is that the plugin will support this insofar as the results of each match will be recorded. What is does not support is creating a summation of results from different modes and I dont see how you could ever do that in a generic way.

If someone wants to run a competition like this they are more than welcome to export the results of each match to csv and sum them up in whatever way they like.

**Comment by skybaks** [comment]
This is resolved by the implementation of https://github.com/skybaks/pyplanet-cup_manager/blob/master/cup_manager/score_mode/score_mixed.py#L9
