### ISSUE TITLE
Create/edit cups from in-game

### ISSUE THREAD

**Issue by skybaks** [skybaks/pyplanet-cup_manager#63]
From reaby, would like the ability for admins to edit cups from in game.

**Comment by reaby** [comment]
Yep... Would be very cool to admins to edit the cups in game.
an easy way would be to add a <textedit> field and allow admins to paste json to it then just save it :)
Also local.py might be splitted to multiple .json files ?

**Comment by skybaks** [comment]
yes, I didnt think of it at the time but json files is a much nicer solution than the local.py
We should still maintain the local.py support so people dont have to upgrade but im fine with using the json files going forward

**Comment by skybaks** [comment]
I'm looking at using the pyplanet storage driver for fs access and probably storing the json files in UserData/Config/cup_manager/ or UserData/Maps/MatchSettings/cup_manager/. Would that be compatible with your use case @reaby?

**Comment by reaby** [comment]
Matchsettings directory propably better for my usecase, but maybe you can make it configurable if someone else wishes the other location
